#!/usr/bin/env bash
# Starts the whole server side for the end-to-end test, as on the DIP servers but on this runner:
# SQL Server with the db/ scripts and the development data (db/dev), the API (Device sign-in, photos in
# the database, PMS copy on) and the DMZ gateway in front of it. Phones (the emulator) reach the
# gateway at http://10.0.2.2:5090/.
# Needs: SA_PASSWORD (generated by the workflow), docker, dotnet. Logs go to e2e-out/.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/e2e-out"; mkdir -p "$OUT"

docker run -d --name mrsql -p 1433:1433 -e ACCEPT_EULA=Y -e MSSQL_SA_PASSWORD="$SA_PASSWORD" mcr.microsoft.com/mssql/server:2022-latest >/dev/null
docker cp "$ROOT/db" mrsql:/db
for i in $(seq 1 60); do
  docker exec mrsql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -C -Q "SELECT 1" >/dev/null 2>&1 && break
  sleep 2
done
docker exec mrsql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -C -b -Q "IF DB_ID('MeterReading') IS NULL CREATE DATABASE MeterReading"

# The order of api/README.md "Run locally", plus 012.
for f in dev/000_create_dev_source_views.sql 002_create_mr_schema.sql 003_meter_id_as_text.sql 004_add_expected_photos.sql \
         005_reading_tenant_and_export.sql 006_pms_transfer.sql 007_reading_image_data.sql 009_device_keys.sql \
         010_field_inspection.sql 012_inspection_location.sql 013_device_reader_binding.sql dev/010_seed_dev_readings.sql dev/020_create_dev_maintain_meter_reading.sql; do
  echo "== db/$f"
  docker exec mrsql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -C -b -d MeterReading -i "/db/$f" > "$OUT/db-$(basename "$f" .sql).txt" 2>&1 \
    || { cat "$OUT/db-$(basename "$f" .sql).txt"; exit 1; }
done

CONN="Server=127.0.0.1,1433;Database=MeterReading;User Id=sa;Password=$SA_PASSWORD;Encrypt=True;TrustServerCertificate=True;Application Name=MeterReadingApi"

dotnet publish "$ROOT/api/src/MeterReading.Api" -c Release -o "$OUT/api-bin" > "$OUT/api-build.txt" 2>&1 || { tail -n 60 "$OUT/api-build.txt"; exit 1; }
dotnet publish "$ROOT/gateway/src/MeterReading.Gateway" -c Release -o "$OUT/gateway-bin" > "$OUT/gateway-build.txt" 2>&1 || { tail -n 60 "$OUT/gateway-build.txt"; exit 1; }

# The API as in production: Device sign-in, trusts the gateway's X-Forwarded-For, PMS copy every 10 s.
(
  cd "$OUT/api-bin"
  ASPNETCORE_ENVIRONMENT=Production ASPNETCORE_URLS=http://127.0.0.1:5080 \
  ConnectionStrings__MeterReading="$CONN" Auth__Mode=Device ImageStore__Kind=Database SourceViews__HasReadingHistory=true \
  Inspection__OfficeLatitude=24.999906 Inspection__OfficeLongitude=55.170344 \
  PmsTransfer__Enabled=true PmsTransfer__IntervalSeconds=10 Gateway__KnownProxies__0=127.0.0.1 \
  nohup dotnet MeterReading.Api.dll > "$OUT/api.log" 2>&1 &
)
# The DMZ gateway, the only address phones know.
(
  cd "$OUT/gateway-bin"
  ASPNETCORE_ENVIRONMENT=Production ASPNETCORE_URLS=http://0.0.0.0:5090 Gateway__ApiBaseUrl=http://127.0.0.1:5080/ \
  nohup dotnet MeterReading.Gateway.dll > "$OUT/gateway.log" 2>&1 &
)

for i in $(seq 1 60); do
  if curl -fsS http://127.0.0.1:5080/health/ready >/dev/null 2>&1; then break; fi
  sleep 2
done
echo "API ready: $(curl -sS http://127.0.0.1:5080/health/ready || true)"
curl -fsS http://127.0.0.1:5080/health/ready >/dev/null || { tail -n 80 "$OUT/api.log"; exit 1; }
# Through the gateway, unsigned: refused, which proves the gateway passes requests to the API.
echo "Gateway /api/v1/me without a key: HTTP $(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:5090/api/v1/me)"
